### ISSUE TITLE
segment.py passes 5 arguments but infer.py requires 4

### ISSUE THREAD

**Issue by sarapapi** [mt-upc/SHAS#1]
Hi all,
I have successfully installed your repo and downloaded your English ckpt.
When I run the segment.py script I got the error:
```
Traceback (most recent call last):
  File "/home/ubuntu/SHAS/./src/supervised_hybrid/segment.py", line 342, in <module>
    segment(args)
  File "/home/ubuntu/SHAS/./src/supervised_hybrid/segment.py", line 236, in segment
    probs, _ = infer(
TypeError: infer() takes 4 positional arguments but 5 were given
```
This is due to the fact that [here](https://github.com/mt-upc/SHAS/blob/2fb7061e0dc5312719ebabadf3900fbf12a271b1/src/supervised_hybrid/segment.py#L236) the wav_path.name is also passed while being useless for the infer function.
If you remove it, the script perfectly works.

**Comment by johntsi** [comment]
Hi @sarapapi, thanks for pointing it out. Commit c9efe6c5ecaa308f1dee563c48959c3fe007c3e2 fixes it :)
